---
# playbook.yml
- name: Install and Configure Web Application
  hosts: webservers
  become: true
  vars_files:
    - vars/webapp_vars.yml
  
  tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache web server
      ansible.builtin.package:
        name: "{{ apache_package }}"
        state: present

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes

    - name: Create web application directory
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Deploy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ app_directory }}/index.html"
        mode: '0644'
      notify: Restart Apache

    - name: Deploy application configuration
      ansible.builtin.template:
        src: templates/webapp.conf.j2
        dest: "{{ apache_conf_dir }}/webapp.conf"
        mode: '0644'
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: "{{ apache_service }}"
        state: restarted
