---
- name: Install and Configure Web Server
  hosts: webservers
  become: yes
  
  vars:
    webserver_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    webserver_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    app_name: "My Web Application"
    app_path: "/var/www/html"
    
  tasks:
    - name: Ensure webserver is installed
      package:
        name: "{{ webserver_package }}"
        state: present
      
    - name: Ensure webserver is started
      service:
        name: "{{ webserver_service }}"
        state: started
        enabled: yes
        
    - name: Create application directory
      file:
        path: "{{ app_path }}"
        state: directory
        mode: '0755'
        
    - name: Deploy index page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>{{ app_name }}</title>
          </head>
          <body>
              <h1>Welcome to {{ app_name }}</h1>
              <p>This site was deployed using Ansible Automation Platform</p>
              <p>Server: {{ ansible_hostname }}</p>
              <p>IP Address: {{ ansible_default_ipv4.address }}</p>
          </body>
          </html>
        dest: "{{ app_path }}/index.html"
        mode: '0644'
      notify: restart webserver
        
  handlers:
    - name: restart webserver
      service:
        name: "{{ webserver_service }}"
        state: restarted

